# Generated by Django 3.1.7 on 2021-03-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0010_remove_storycomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userpage.storycomment'),
        ),
    ]
