# Generated by Django 3.1.4 on 2021-03-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0015_possibleanswers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PossibleAnswers',
        ),
    ]
