# Generated by Django 3.1.4 on 2021-03-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0017_possibleanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(blank=True, default='default/default.png', upload_to='Profiles'),
        ),
    ]
