# Generated by Django 3.1.4 on 2021-03-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0020_auto_20210306_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userImage',
        ),
    ]
