# Generated by Django 3.1.4 on 2021-03-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0021_auto_20210306_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='default/default_pic.jpg', upload_to='Profiles'),
        ),
    ]
