# Generated by Django 3.1.4 on 2021-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0022_profile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='True', upload_to='Post'),
        ),
    ]
