# Generated by Django 3.1.4 on 2021-03-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0023_auto_20210308_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
